config/routes.rb
Rails.application.routes.draw do
  root 'images#index'

  resources :users
  resources :images
  resources :likes

  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  delete "logout"  => "sessions#destroy"
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/image_similarity_point.rb
class ImageSimilarityPoint < ActiveRecord::Base
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :image
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :pre_process, except: :destroy

  private
  def pre_process
    return if params[:controller] == "sessions"
    redirect_to login_path unless logged_in?
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    # todo 最適化された順番で取得
    unless params[:image_id].present?
      @image = Image.find(rand(1..1800))
    else
      @image = Image.find(params[:image_id])
    end

    @like = Like.find_by user_id: current_user.id, image_id: @image.id
    @like = Like.new unless @like.present?
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:url)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    Like.create user_id: current_user.id, image_id: params[:like][:image_id]
    update_similarity_point
    @image = get_next_image
  end

  private
  def update_similarity_point
    base_user_ids = Like.where(image_id: params[:like][:image_id]).pluck :user_id
    Image.all.each do |image|
      user_ids = Like.where(image_id: image.id).pluck :user_id
      point = ImageSimilarityPoint.find_by image_id_1: image.id, image_id_2: params[:like][:image_id]
      unless point.present?
        point = ImageSimilarityPoint.find_by image_id_2: image.id, image_id_1: params[:like][:image_id]
      end

      likes_hash = {
        params[:like][:image_id] => base_user_ids,
        image.id => user_ids
      }
      if point.present?
        point.update point: RecommendService.caculate_similarity_point(likes_hash)
      else
        ImageSimilarityPoint.create image_id_1: params[:like][:image_id], image_id_2: image.id
      end
    end
  end

  def get_next_image
    condition = "image_id_1 = #{params[:like][:image_id]} || image_id_2 = #{params[:like][:image_id]}"
    point = ImageSimilarityPoint.where(condition).order(point: :desc).first
    return Image.find rand(1..1800) unless point.present?
    Image.find_by id: point.image_id_1
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Login successfully!"
      log_in user
      redirect_to root_path
    else
      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      ### TODO
      flash[:success] = "アカウント作成は完了しました。"
      redirect_to root_path
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
      :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<div class="main-container col-md-12">
  <%= image_tag @image.url %>
</div>

<div>
  <%= form_for @like, remote: true, url: likes_path, method: :post do |f| %>
    <%= f.hidden_field :image_id, value: @image.id %>
    <% if @like.id.present? %>
      <%= f.submit "可愛いね", class: "sbt_1", id: "like", disabled: true %>
    <% else %>
      <%= f.submit "可愛いね", class: "sbt_1", id: "like" %>
    <% end %>
    <a href="http://localhost:3000" id="next">
      次へ
    </a>
  <% end %>
</div>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @image.url %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iiko</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'login_signup', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/likes/create.js.erb
document.getElementById("like").disabled = true;
document.getElementById("next").href = "http://localhost:3000?image_id=<%= @image.id %>"

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(obj.errors.count, "error") %>.
    </div>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="login-page">
  <div class="form">
    <%= form_for @user, class: "register-form" do |f| %>
      <%= render "shared/error_messages" %>
      <%= f.email_field :email, placeholder: "メールを入力してください。" %>
      <%= f.text_field :name, placeholder: "名前を入力してください。" %>
      <%= f.password_field :password, placeholder: "パスワードを入力してください。" %>
      <%= f.password_field :password_confirmation, placeholder: "パスワードをもう一度入力してください。" %>
      <%= f.submit "アカウントを作成する" %>
      <p class="message">アカウントがあった場合は <a href="#">ログインする</a></p>
    <% end %>
  </div>
</div>